/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author User
 */
public class Entradas extends javax.swing.JFrame {

    /**
     * Creates new form menualimentos
     */
    public Entradas() {
        initComponents();
    }
    public String bd = "escuela";
    public String user = "root";
    public String pwd = "";
    public String url = "jdbc:mysql://localhost/restaurant";
    public String driver = "com.mysql.cj.jdbc.Driver";
    Connection conn = null;
    Statement stmt = null;

    public void Seleccion() {
        try {
            Class.forName(driver);
            conn = (Connection) DriverManager.getConnection(url, user, pwd);
            System.out.println("Conexion exitosa");
            if (Consome.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (6, 'Consome', 60)";
                stmt.executeUpdate(query1);
                Consome.setSelected(false);

            }
            if (Camaron.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (7, 'Camaron', 110)";
                stmt.executeUpdate(query1);
                Camaron.setSelected(false);
            }
            if (CamaronP.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (8, 'Camaron Pelado', 175)";
                stmt.executeUpdate(query1);
                CamaronP.setSelected(false);
            }
            if (Sopa.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (9, 'Sopa de mariscos', 250)";
                stmt.executeUpdate(query1);
                Sopa.setSelected(false);
            }
            if (Campechano.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (10, 'Campechano', 190)";
                stmt.executeUpdate(query1);
                Campechano.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println("Error");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Consome = new javax.swing.JCheckBox();
        Camaron = new javax.swing.JCheckBox();
        CamaronP = new javax.swing.JCheckBox();
        Sopa = new javax.swing.JCheckBox();
        Campechano = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(147, 118, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel1.setText("CAMARÓN");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 177, 178, -1));
        jLabel1.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel3.setText("CONSOMÉ");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 130, 178, -1));
        jLabel3.getAccessibleContext().setAccessibleName("");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setText("CAMARÓN PELADO");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 216, 178, -1));
        jLabel4.getAccessibleContext().setAccessibleName("");

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setText("SOPA DE MARISCOS");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 255, 178, -1));
        jLabel5.getAccessibleContext().setAccessibleName("");

        jLabel6.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel6.setText("CAMPECHANO");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 298, 178, -1));
        jLabel6.getAccessibleContext().setAccessibleName("");

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel8.setText("$60");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 129, 77, -1));

        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel9.setText("$110");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 177, 77, -1));

        jLabel10.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel10.setText("$175");
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 216, 77, -1));

        jLabel11.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel11.setText("$250");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 255, 77, -1));

        jLabel12.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel12.setText("$190");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 298, 77, -1));

        Consome.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        Consome.setText("AGREGAR");
        jPanel1.add(Consome, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 129, -1, -1));

        Camaron.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        Camaron.setText("AGREGAR");
        Camaron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamaronActionPerformed(evt);
            }
        });
        jPanel1.add(Camaron, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 172, -1, -1));

        CamaronP.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        CamaronP.setText("AGREGAR");
        CamaronP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamaronPActionPerformed(evt);
            }
        });
        jPanel1.add(CamaronP, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 215, -1, -1));

        Sopa.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        Sopa.setText("AGREGAR");
        jPanel1.add(Sopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 254, -1, -1));

        Campechano.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        Campechano.setText("AGREGAR");
        Campechano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampechanoActionPerformed(evt);
            }
        });
        jPanel1.add(Campechano, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 297, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fish1.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 13, -1, -1));

        jLabel7.setBackground(new java.awt.Color(232, 147, 207));
        jLabel7.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Entradas");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 13, 264, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fish.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 13, -1, -1));

        jButton1.setText("Agregar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jMenu5.setText("Inicio");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu2.setText("Bebidas");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cocteles");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Platos Fuertes");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CamaronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamaronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamaronActionPerformed

    private void CamaronPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamaronPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamaronPActionPerformed

    private void CampechanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampechanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampechanoActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        this.dispose();
        new PantallaPrincipal().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.dispose();
        new Bebidas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        this.dispose();
        new Cocteles().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        this.dispose();
        new PlatosFuertes().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Seleccion();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Camaron;
    private javax.swing.JCheckBox CamaronP;
    private javax.swing.JCheckBox Campechano;
    private javax.swing.JCheckBox Consome;
    private javax.swing.JCheckBox Sopa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
