/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author enano
 */
public class PlatosFuertes extends javax.swing.JFrame {

    public String bd = "escuela";
    public String user = "root";
    public String pwd = "";
    public String url = "jdbc:mysql://localhost/restaurant";
    public String driver = "com.mysql.cj.jdbc.Driver";
    Connection conn = null;
    Statement stmt = null;

    public void Seleccion() {
        try {
            Class.forName(driver);
            conn = (Connection) DriverManager.getConnection(url, user, pwd);
            System.out.println("Conexion exitosa");
            if (FileteF.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (11, 'Filete frito', 50)";
                stmt.executeUpdate(query1);
                FileteF.setSelected(false);

            }
            if (FileteC.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (12, 'Filete con camaron', 60)";
                stmt.executeUpdate(query1);
                FileteC.setSelected(false);
            }
            if (FileteA.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (13, 'Filete con arroz y papas', 60)";
                stmt.executeUpdate(query1);
                FileteA.setSelected(false);
            }
            if (PescadoR.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (14, 'Pescado relleno', 200)";
                stmt.executeUpdate(query1);
                PescadoR.setSelected(false);
            }
            if (PescadoE.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (15, 'Pescado enchilado', 180)";
                stmt.executeUpdate(query1);
                PescadoE.setSelected(false);
            }
            if (PescadoEM.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (16, 'Pescado empapelado', 150)";
                stmt.executeUpdate(query1);
                PescadoEM.setSelected(false);
            }
            if (Mojarra.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (17, 'Mojarra', 190)";
                stmt.executeUpdate(query1);
                Mojarra.setSelected(false);
            }
            if (Piña.isSelected()) {
                stmt = (Statement) conn.createStatement();
                String query1 = "INSERT INTO pedidos " + "VALUES (18, 'Piña rellena', 210)";
                stmt.executeUpdate(query1);
                Piña.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println("Error");
        }

    }

    /**
     * Creates new form NewJFrame
     */
    public PlatosFuertes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        FileteF = new javax.swing.JCheckBox();
        FileteC = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        FileteA = new javax.swing.JCheckBox();
        PescadoR = new javax.swing.JCheckBox();
        PescadoE = new javax.swing.JCheckBox();
        PescadoEM = new javax.swing.JCheckBox();
        Mojarra = new javax.swing.JCheckBox();
        Piña = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(147, 118, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel1.setBackground(new java.awt.Color(232, 147, 207));
        jLabel1.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel1.setText("Platos Fuertes");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setText("FILETE CON CAMARÓN");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel3.setText("FILETE CON ARROZ Y PAPAS");
        jLabel3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setText("FILETE FRITO");
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setText("PESCADO RELLENO");
        jLabel5.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel6.setText("PESCADO ENCHILADO");
        jLabel6.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel7.setText("PESCADO EMPAPELADO");
        jLabel7.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel8.setText("MOJARRA");
        jLabel8.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel9.setText("PIÑA RELLENA");
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel10.setText("$60");
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel11.setText("$50");
        jLabel11.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel12.setText("$200");
        jLabel12.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel13.setText("$60");
        jLabel13.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel15.setText("$150");
        jLabel15.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel16.setText("$210");
        jLabel16.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel17.setText("$190");
        jLabel17.setOpaque(true);

        FileteF.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        FileteF.setText("AGREGAR");
        FileteF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileteFActionPerformed(evt);
            }
        });

        FileteC.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        FileteC.setText("AGREGAR");
        FileteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileteCActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel14.setText("$180");
        jLabel14.setOpaque(true);

        FileteA.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        FileteA.setText("AGREGAR");
        FileteA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileteAActionPerformed(evt);
            }
        });

        PescadoR.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        PescadoR.setText("AGREGAR");
        PescadoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PescadoRActionPerformed(evt);
            }
        });

        PescadoE.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        PescadoE.setText("AGREGAR");
        PescadoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PescadoEActionPerformed(evt);
            }
        });

        PescadoEM.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        PescadoEM.setText("AGREGAR");
        PescadoEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PescadoEMActionPerformed(evt);
            }
        });

        Mojarra.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        Mojarra.setText("AGREGAR");
        Mojarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MojarraActionPerformed(evt);
            }
        });

        Piña.setFont(new java.awt.Font("Ebrima", 2, 12)); // NOI18N
        Piña.setText("AGREGAR");
        Piña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiñaActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fish1.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fish.png"))); // NOI18N

        jButton1.setText("Agregar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Piña)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Mojarra, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PescadoEM, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PescadoE, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PescadoR, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FileteA, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FileteF, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FileteC, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileteF)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileteC)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileteA)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PescadoR)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PescadoE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PescadoEM)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Mojarra)
                            .addComponent(jLabel17)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Piña)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenu5.setText("Inicio");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu1.setText("Entradas");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bebidas");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cocteles");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FileteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileteCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileteCActionPerformed

    private void FileteAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileteAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileteAActionPerformed

    private void PescadoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PescadoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PescadoRActionPerformed

    private void PescadoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PescadoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PescadoEActionPerformed

    private void PescadoEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PescadoEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PescadoEMActionPerformed

    private void MojarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MojarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MojarraActionPerformed

    private void PiñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PiñaActionPerformed

    private void FileteFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileteFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileteFActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        this.dispose();
        new Bebidas().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        this.dispose();
        new PantallaPrincipal().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.dispose();
        new Entradas().setVisible(true);        // TODO add your handling code here:(
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        this.dispose();
        new Cocteles().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Seleccion();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlatosFuertes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FileteA;
    private javax.swing.JCheckBox FileteC;
    private javax.swing.JCheckBox FileteF;
    private javax.swing.JCheckBox Mojarra;
    private javax.swing.JCheckBox PescadoE;
    private javax.swing.JCheckBox PescadoEM;
    private javax.swing.JCheckBox PescadoR;
    private javax.swing.JCheckBox Piña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
